version: "3"
services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`co2footprintcalculator.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    ports:
      - 8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    image: backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=OlW5YN6jMJykEqXB
      - MONGODB_DATABASE=CO2footprint
      - MONGODB_CONNECTION_STRING=mongodb://mongo/co2-footprint-calculator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`co2footprintcalculator.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/socket`)))"
      - "traefik.http.routers.backend.entrypoints=web"
    ports:
      - 3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./images:/app/images
  mongo:
    image: mongo
    ports:
      - 27017:27017
  load-balancer:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
