version: "3"
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=erkaltufekci
      - MONGODB_PASSWORD=SVWMWKNsRidvyHXS
      - MONGODB_DATABASE=CO2footprint
      - MONGODB_CONNECTION_STRING=mongodb://mongo/co2-footprint-calculator
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
